#include <EEPROM.h>

#define EEPROM_SIZE 255

#define OUT1_DEFAULT_STATE_EEPROM_ADDRESS 1
#define OUT2_DEFAULT_STATE_EEPROM_ADDRESS 2
#define OUT3_DEFAULT_STATE_EEPROM_ADDRESS 3
#define OUT4_DEFAULT_STATE_EEPROM_ADDRESS 4
#define OUT5_DEFAULT_STATE_EEPROM_ADDRESS 5

#define VE_CHARGER_DEFAULT_STATE_EEPROM_ADDRESS 6


void eeprom_init(){
  EEPROM.begin(EEPROM_SIZE);

  board_io.output1 = EEPROM.read(OUT1_DEFAULT_STATE_EEPROM_ADDRESS);
  board_io.output2 = EEPROM.read(OUT2_DEFAULT_STATE_EEPROM_ADDRESS);
  board_io.output3 = EEPROM.read(OUT3_DEFAULT_STATE_EEPROM_ADDRESS);
  board_io.output4 = EEPROM.read(OUT4_DEFAULT_STATE_EEPROM_ADDRESS);
  board_io.output5 = EEPROM.read(OUT5_DEFAULT_STATE_EEPROM_ADDRESS);

  ve_data.enable_charger = EEPROM.read(VE_CHARGER_DEFAULT_STATE_EEPROM_ADDRESS);
}
